parser: babel-eslint
extends:
- airbnb-base
env:
  mocha: true
  meteor: true
rules:
  arrow-parens: off
  max-len:
  - warn
  - code: 120
    ignoreTrailingComments: true
    ignoreUrls: true
  padded-blocks: off
  react/prop-types: off
  semi:
  - error
  - never
  space-unary-ops:
  - error
  - overrides:
      "!": true
  quote-props: off
  no-confusing-arrow: off
  no-unused-expressions: off
  no-underscore-dangle: off
  no-param-reassign:
  - error
  - props: false
  no-trailing-spaces: off
  no-lonely-if: off   # Allows us to be clearer at times
  class-methods-use-this: off
  import/named: error
  import/no-extraneous-dependencies: off
  import/prefer-default-export: off
  import/extensions:
  - off
  - never
  import/no-unresolved:
  - error
  - ignore:
    - "^react$"  # since we can't install it as a dependency
    - "^react-dom$"
  react/no-did-mount-set-state: off
ecmaFeatures:
  spread: true
settings:
  import/resolver:
    meteor:
      extensions:
      - ".js"
      - ".jsx"
